### ISSUE TITLE
Using multiple nested keys throws error (#9), found a fix which works, but your tests have failed. Any side effects expected ?

### ISSUE THREAD

**Issue by DhavalW** [deepstreamIO/deepstream.io-storage-mongodb#12]
( Apologies, Wasn't sure how to re-open or request re-opening of a previously closed issue (#9), so creating a new one. New to the github process. Reposting below ) 

Faced the same issue as in #9 recently, despite being closed. Have fixed it at my end and submitted pull request #11  and it seems to be working correctly for now, but your tests on the pull request have failed. Does that imply any side effects ? Please advise !

using
mongodb storage connector 1.1.0
deepstream 2.3.6

on Digital Ocean, configured according to the official Deepstream Digital ocean tutorial using deepstream + redis + mongodb.

the pull request has failed checks with the message  - " expected 'a/b' to equal 'a' "

**Comment by yasserf** [comment]
Hey @DhavalW 

Thanks for raising the PR/Issue. I believe the behaviour in all our connectors is to take the first slash as the split character and not the last.

This change will also break compatability with all users of the current mongodb adaptor. Because of that I'm afraid.

It looks like adaptor hasn't been released yet. We will look into that shorty. Thanks

**Comment by DhavalW** [comment]
Yep. Thanks for clarifying @yasserf . 

I believe thats how the connector is originally implemented. but that seems to break functionality with mongodb. I get invalid key errors for anything more than a single nesting.

Eg: 
" /server/taxonomies/base/0 "  ( with 0 as the record id) breaks with error invalid key  

So i tested with base0 instead of 0 as " /server/taxonomies/base/base0 " , just in case the name 0 as a key name was an issue. but no difference. it still broke.

But once i changed the connector code to lastIndexOf... it worked fine, even with the original record path.

Any ideas why ? Am i doing something wrong?

**Comment by yasserf** [comment]
Are you trying master?

**Comment by DhavalW** [comment]
the "deepstream install" log shows mongodb storage connector as version 1.1.0 when installing.
I'm not sure how to identify the branch as master (or not)

**Comment by DhavalW** [comment]
Something just occurred to me. 
do you think a leading slash could be the issue ? since the connector uses indexOf, which returns only the first index, A leading slash in the path that might cause the collection name to be "".


"/server/taxonomies/base/0 " 
VS 
"server/taxonomies/base/0 "

**Comment by yasserf** [comment]
hey

Yup, that could most probably be it! We have seen that problem occur before, I just totally forgot about it. Can you try without it?

**Comment by DhavalW** [comment]
Yup. that solved it. seems to be working fine now.
Thanks for your help

**Comment by DhavalW** [comment]
Maybe its a good idea to mention this in the documentation somewhere. Especially since the Official deepstream tutorial for digital ocean setup includes mongodb.
