### ISSUE TITLE
Pagination list records ?

### ISSUE THREAD

**Issue by codecrack3** [deepstreamIO/deepstream.io-storage-mongodb#25]
How can i do pagination list records . ? . Example `record.list('chats/*', { start: 0, limit: 256 }, ({ ids }) => console.log(ids))`

**Comment by valentinvichnal** [comment]
You can't do pagination with the mongodb plugin, this only works with rethinkdb at the moment.

I might try to add pagination in the future.
A good workaround if you create new Lists `record.list('chats0-256/*',` and fetch records from the database directly.

**Comment by yasserf** [comment]
This logic would need to be implemented in the real-time search provider.

However to compete with featherJS and other frameworks we might need to add it to the actually storage interface. Question is how, given that the main reason it’s in the provider is to stop the same real-time queries being registered across more than one instance.

**Comment by valentinvichnal** [comment]
I agree the real-time provider should do this and the storage should remain simple.

Pagination is nice but not at the expense of performance.
Some real time projects I worked with used to rely on MongoDB oplog and cursor for pagination, these became very slow with more queries, though MongoDB solved a lot of issues in new versions.

Fetching the database in a timeout and setting the entries in a new List works well for me.

**Comment by codecrack3** [comment]
Thank you for solutions. I think i have an answer :D
