### ISSUE TITLE
Using multiple nested keys throws error

### ISSUE THREAD

**Issue by mfdeux** [deepstreamIO/deepstream.io-storage-mongodb#9]
# Issue
Using a key like x/y/z presents an error when using mongodb as the storage back-end.  Using a key like x/y works as intended.  Basically any key with more than one nesting throws error.

# Environment
Latest docker
Latest image pulled from deepstream/deepstream.io
Latest mongoDb image from DockerHub

Example client code:
"const record = deepstreamClient.record.getRecord('settings/user/hi')"

Example server config:
Stock config except mongodb backend:
  storage:
    name: mongodb
    options:
      connectionString: 'mongodb://mongodb:27017'
      database: 'deepstream'
      defaultTable: 'toplevel'
      splitChar: '/'

Server error:
RECORD_LOAD_ERROR | error while loading settings/user/hi from storage:Invalid key settings/user/hi

**Comment by valentinvichnal** [comment]
It was solved in 1.1.0, but the latest npm release is still 1.0.2.
Try to use the source manually.

**Comment by mfdeux** [comment]
@valentinvichnal This worked, thanks.

**Comment by DhavalW** [comment]
Faced the same issue again, just now.

using
 mongodb storage connector  1.1.0 
 deepstream 2.3.6 

on Digital Ocean, configured according to the official Digital ocean tutorial using deepstream + redis + mongodb.

Did some digging & seem to have found a fix which i've implemented at my end and the errors have disappeared. please see my pull request

though, NOT SURE IF ANY SIDE EFFECTS ? please advise.
